apiVersion: v1
kind: Service
metadata:
  name: shopping-cart-service
  namespace: default
  labels:
    devops.lab.exercise: "10"
spec:
  selector:
    app: shopping-cart
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
