name: exercise7
services:
  jenkins:
    image: jenkins/jenkins:lts
    environment:
      JAVA_OPTS: -Xmx512m
    ports:
      - "127.0.0.1:18007:8080"
      - "127.0.0.1:15007:50000"
    volumes:
      - jenkins-home:/var/jenkins_home
    labels:
      devops.lab.exercise: "7"
volumes:
  jenkins-home:
    labels:
      devops.lab.exercise: "7"
